application: fungi-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: app.main
  login: required

libraries:
- name: ssl
  version: latest

skip_files:
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\..*$


